name: ambasada
on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:
jobs:
  ambasada:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.5"
      - name: Create venv
        run: make init
      - name: Run
        run: make run-ambasada
      - name: Save
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: Update ambasada
